# Generated by Django 5.0.6 on 2024-10-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_file_created_at_remove_file_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfolderpermission',
            name='can_manage',
            field=models.BooleanField(default=False),
        ),
    ]
