# Generated by Django 5.0.4 on 2024-05-14 14:59

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[home.models.validate_file_extension]),
        ),
    ]
