# Generated by Django 5.0.4 on 2024-05-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_folder_users_with_access_alter_folder_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FolderInvitation',
        ),
    ]
